include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**

formatter:
  page_width: 80
  trailing_commas: automate

linter:
  rules:
    - directives_ordering
    - prefer_relative_imports
    - prefer_single_quotes
