import 'package:zuno/core/notifications/notification_delivery_mode.dart';
import 'package:zuno/core/platform/app_platform.dart';
import 'package:zuno/core/platform/platform_capabilities.dart';

final androidCapabilities = capabilitiesFor(AppPlatform.android);

final iosCapabilities = capabilitiesFor(AppPlatform.ios);

PlatformCapabilities capabilitiesLike(
  PlatformCapabilities base, {
  bool? batteryExemption,
  bool? backgroundDataRestriction,
  bool? fullScreenIntent,
  bool? homeScreenShortcuts,
  bool? screenSecurity,
  bool? screenshotBlocking,
  bool? sensitiveClipboard,
  bool? lockScreenCallUi,
  bool? nativeRingbackTone,
  bool? callForegroundService,
  bool? headlessWakeLocks,
  bool? notificationImages,
  bool? apnsRegistration,
  bool? nativeIncomingRingUi,
  bool? callKit,
  bool? vibrationPatterns,
  bool? inboundShare,
  bool? pictureInPicture,
  bool? nativeImageResize,
  bool? nativeVideoTools,
  bool? uploadForegroundService,
  bool? networkAvailabilityEvents,
  bool? nativeSignOutWipe,
  bool? signOutWipeKeepsProcess,
  bool? atomicDatabaseBatches,
  bool? nativeRoomOpens,
  bool? clientLease,
  bool? instantPushNotices,
  bool? notificationAvatars,
  bool? pushDiagnostics,
  bool? voipRing,
  bool? nseNotifications,
  bool? nativeNotificationActions,
  List<NotificationDeliveryMode>? deliveryModes,
  NotificationDeliveryMode? defaultDeliveryMode,
}) => PlatformCapabilities(
  batteryExemption: batteryExemption ?? base.batteryExemption,
  backgroundDataRestriction:
      backgroundDataRestriction ?? base.backgroundDataRestriction,
  fullScreenIntent: fullScreenIntent ?? base.fullScreenIntent,
  foregroundSyncService: base.foregroundSyncService,
  homeScreenShortcuts: homeScreenShortcuts ?? base.homeScreenShortcuts,
  screenSecurity: screenSecurity ?? base.screenSecurity,
  screenshotBlocking: screenshotBlocking ?? base.screenshotBlocking,
  sensitiveClipboard: sensitiveClipboard ?? base.sensitiveClipboard,
  lockScreenCallUi: lockScreenCallUi ?? base.lockScreenCallUi,
  nativeRingbackTone: nativeRingbackTone ?? base.nativeRingbackTone,
  callForegroundService: callForegroundService ?? base.callForegroundService,
  autostartSettings: base.autostartSettings,
  headlessWakeLocks: headlessWakeLocks ?? base.headlessWakeLocks,
  notificationImages: notificationImages ?? base.notificationImages,
  vibrationPatterns: vibrationPatterns ?? base.vibrationPatterns,
  deviceSafetyChecks: base.deviceSafetyChecks,
  inboundShare: inboundShare ?? base.inboundShare,
  nativeSignOutWipe: nativeSignOutWipe ?? base.nativeSignOutWipe,
  nativeImageResize: nativeImageResize ?? base.nativeImageResize,
  nativeVideoTools: nativeVideoTools ?? base.nativeVideoTools,
  uploadForegroundService:
      uploadForegroundService ?? base.uploadForegroundService,
  networkAvailabilityEvents:
      networkAvailabilityEvents ?? base.networkAvailabilityEvents,
  keyboardLearningOptOut: base.keyboardLearningOptOut,
  apnsRegistration: apnsRegistration ?? base.apnsRegistration,
  nativeIncomingRingUi: nativeIncomingRingUi ?? base.nativeIncomingRingUi,
  callKit: callKit ?? base.callKit,
  pictureInPicture: pictureInPicture ?? base.pictureInPicture,
  playerNeedsMediaType: base.playerNeedsMediaType,
  videoCodecOrder: base.videoCodecOrder,
  recorderWritesOgg: base.recorderWritesOgg,
  callMuteByInputMixer: base.callMuteByInputMixer,
  signOutWipeKeepsProcess:
      signOutWipeKeepsProcess ?? base.signOutWipeKeepsProcess,
  locationServicesSettings: base.locationServicesSettings,
  filesTypedByExtension: base.filesTypedByExtension,
  atomicDatabaseBatches: atomicDatabaseBatches ?? base.atomicDatabaseBatches,
  nativeRoomOpens: nativeRoomOpens ?? base.nativeRoomOpens,
  clientLease: clientLease ?? base.clientLease,
  instantPushNotices: instantPushNotices ?? base.instantPushNotices,
  notificationAvatars: notificationAvatars ?? base.notificationAvatars,
  pushDiagnostics: pushDiagnostics ?? base.pushDiagnostics,
  voipRing: voipRing ?? base.voipRing,
  nseNotifications: nseNotifications ?? base.nseNotifications,
  nativeNotificationActions:
      nativeNotificationActions ?? base.nativeNotificationActions,
  videoRendererNeedsDetach: base.videoRendererNeedsDetach,
  cameraStopsInBackground: base.cameraStopsInBackground,
  deliveryModes: deliveryModes ?? base.deliveryModes,
  defaultDeliveryMode: defaultDeliveryMode ?? base.defaultDeliveryMode,
);
