name: master

on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
    with:
      coverage: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
